---
AWSTemplateFormatVersion: '2010-09-09'
Description: 'AWS CloudFormation Sample Template'

Parameters:
  VPCId:
    Description: Default VPC
    Type: List<AWS::EC2::VPC::Id>
    Default: "vpc-ace867c8"
  KeyName:
    Description: Name of an existing EC2 KeyPair to enable SSH access to the instance
    Type: AWS::EC2::KeyPair::KeyName
    Default: Jenkins_Again
    ConstraintDescription: must be the name of an existing EC2 KeyPair.
  InstanceType:
    Description: WebServer EC2 instance type
    Type: String
    Default: t2.micro
    AllowedValues:
    - t1.micro
    - t2.nano
    - t2.micro
    - t2.small
    ConstraintDescription: must be a valid EC2 instance type.
  WebSecurityGroup: 
    Description: Web SG Group
    Type: AWS::EC2::SecurityGroup::Id
    Default: sg-01ebb12e46cc54194

Resources:
  EC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: !Ref InstanceType
      SecurityGroupIds:
      - !Ref WebSecurityGroup
      KeyName:
        Ref: KeyName
      ImageId: ami-0e98a3611edf495f1
      UserData: 
        Fn::Base64:
          !Sub |
              #cloud-boothook
              #!/bin/sh
              touch test.txt

Outputs:
  InstanceIp:
    Description: Web Server Public Ip
    Value: !GetAtt EC2Instance.PublicIp


